<?php

declare(strict_types=1);

namespace LaraMint\LaravelBrain\Graph;

use LaraMint\LaravelBrain\Analysis\CallChainEdge;
use LaraMint\LaravelBrain\Analysis\ChannelDefinition;
use LaraMint\LaravelBrain\Analysis\ConsoleCommandDefinition;
use LaraMint\LaravelBrain\Analysis\ControllerDefinition;
use LaraMint\LaravelBrain\Analysis\DbQuery;
use LaraMint\LaravelBrain\Analysis\FlowExtractor;
use LaraMint\LaravelBrain\Analysis\MiddlewareRegistry;
use LaraMint\LaravelBrain\Analysis\ModelDefinition;
use LaraMint\LaravelBrain\Analysis\ProjectStructure;
use LaraMint\LaravelBrain\Analysis\RouteDefinition;
use LaraMint\LaravelBrain\Analysis\ScheduleEntry;
use LaraMint\LaravelBrain\Parser\PhpFileParser;
use PhpParser\Node as PhpNode;
use PhpParser\NodeTraverser;
use PhpParser\NodeVisitor;
use PhpParser\NodeVisitorAbstract;

class GraphBuilder
{
    private const LIGHT_MODE_ROUTE_THRESHOLD = 1200;

    private const LIGHT_MODE_CALL_EDGE_THRESHOLD = 6000;

    private Graph $graph;

    private int $edgeCounter = 0;

    private FlowExtractor $flowExtractor;

    private PhpFileParser $parser;

    private ProjectStructure $projectStructure;

    private array $psr4Map = [];

    /** @var string[] */
    private array $classSearchBases = [];

    /** @var array<string, array> file path => parsed result cache */
    private array $parseCache = [];

    /**
     * Accumulator for fat-class detection.
     * Maps controllerId/nodeId => ['totalLines' => int, 'methodCount' => int]
     *
     * @var array<string, array>
     */
    private array $classMetrics = [];

    /** @var array<string, DbQuery[]> "FQCN::method" => DbQuery[] */
    private array $dbQueryMap = [];

    private bool $lightMode = false;

    public function __construct()
    {
        $this->graph = new Graph;
        $this->flowExtractor = new FlowExtractor;
        $this->parser = new PhpFileParser;
        $this->projectStructure = new ProjectStructure;
    }

    /**
     * Build a PSR-4 map that covers both project classes and vendor packages
     * by reading vendor/composer/autoload_psr4.php (generated by Composer).
     */
    private function buildFullPsr4Map(string $projectRoot): array
    {
        $map = $this->projectStructure->buildPsr4Map($projectRoot);

        $autoloadFile = $projectRoot.'/vendor/composer/autoload_psr4.php';
        if (! file_exists($autoloadFile)) {
            return $map;
        }

        // The file uses $vendorDir / $baseDir variables
        $vendorDir = $projectRoot.'/vendor';
        $baseDir = $projectRoot;

        $raw = require $autoloadFile;
        foreach ($raw as $namespace => $paths) {
            foreach ((array) $paths as $path) {
                $ns = rtrim($namespace, '\\');
                if (! isset($map[$ns])) {
                    $map[$ns] = rtrim($path, '/');
                }
                break; // take first path per namespace
            }
        }

        return $map;
    }

    /**
     * Resolve an FQCN to an absolute file path using the PSR-4 map.
     */
    private function resolveFile(string $fqcn): string
    {
        foreach ($this->psr4Map as $namespace => $basePath) {
            if (str_starts_with($fqcn, $namespace.'\\')) {
                $relative = substr($fqcn, strlen($namespace) + 1);
                $path = $basePath.'/'.str_replace('\\', '/', $relative).'.php';
                if (file_exists($path)) {
                    return $path;
                }
            }
        }

        $relative = str_replace('\\', '/', $fqcn).'.php';
        foreach ($this->classSearchBases as $base) {
            $path = $base.'/'.$relative;
            if (file_exists($path)) {
                return $path;
            }
        }

        $fallback = $this->searchByClassName($fqcn);
        if ($fallback !== null) {
            return $fallback;
        }

        return '';
    }

    private function searchByClassName(string $fqcn): ?string
    {
        $shortName = str_contains($fqcn, '\\')
            ? substr($fqcn, strrpos($fqcn, '\\') + 1)
            : $fqcn;
        $filename = $shortName.'.php';

        foreach ($this->classSearchBases as $base) {
            $iterator = new \RecursiveIteratorIterator(
                new \RecursiveDirectoryIterator($base, \FilesystemIterator::SKIP_DOTS)
            );

            foreach ($iterator as $file) {
                if ($file->getFilename() === $filename) {
                    return $file->getPathname();
                }
            }
        }

        return null;
    }

    /**
     * Parse a class file (cached) and extract flow steps for a specific method.
     */
    private function extractMethodFlowSteps(string $fqcn, string $method): array
    {
        $file = $this->resolveFile($fqcn);
        if ($file === '') {
            return [];
        }

        if (! isset($this->parseCache[$file])) {
            $this->parseCache[$file] = $this->parser->parse($file);
        }
        $parsed = $this->parseCache[$file];
        if (! $parsed || ! $parsed['ast']) {
            return [];
        }

        $traverser = new NodeTraverser;
        $finder = new class($method) extends NodeVisitorAbstract
        {
            public ?PhpNode\Stmt\ClassMethod $found = null;

            public function __construct(private string $target) {}

            public function enterNode(PhpNode $node): ?int
            {
                if ($node instanceof PhpNode\Stmt\ClassMethod
                    && $node->name->toString() === $this->target) {
                    $this->found = $node;

                    return NodeVisitor::STOP_TRAVERSAL;
                }

                return null;
            }
        };
        $traverser->addVisitor($finder);
        $traverser->traverse($parsed['ast']);

        if ($finder->found === null) {
            return [];
        }

        return $this->flowExtractor->extract($finder->found, $parsed['useMap'] ?? []);
    }

    /**
     * Compute complexity metrics for a specific method in a class file (cached).
     * Returns an empty array if the file or method cannot be resolved.
     */
    private function extractMethodMetrics(string $fqcn, string $method): array
    {
        $file = $this->resolveFile($fqcn);
        if ($file === '') {
            return [];
        }

        if (! isset($this->parseCache[$file])) {
            $this->parseCache[$file] = $this->parser->parse($file);
        }
        $parsed = $this->parseCache[$file];
        if (! $parsed || ! $parsed['ast']) {
            return [];
        }

        $traverser = new NodeTraverser;
        $finder = new class($method) extends NodeVisitorAbstract
        {
            public ?PhpNode\Stmt\ClassMethod $found = null;

            public function __construct(private string $target) {}

            public function enterNode(PhpNode $node): ?int
            {
                if ($node instanceof PhpNode\Stmt\ClassMethod
                    && $node->name->toString() === $this->target) {
                    $this->found = $node;

                    return NodeVisitor::STOP_TRAVERSAL;
                }

                return null;
            }
        };
        $traverser->addVisitor($finder);
        $traverser->traverse($parsed['ast']);

        if ($finder->found === null) {
            return [];
        }

        return $this->flowExtractor->metrics($finder->found);
    }

    /**
     * @param  RouteDefinition[]  $routes
     * @param  array<string, ControllerDefinition>  $controllers
     * @param  CallChainEdge[]  $callChain
     * @param  array<string, ModelDefinition>  $models
     * @param  array<string, DbQuery[]>  $dbQueryMap  "FQCN::method" => queries
     */
    public function build(
        string $projectName,
        array $routes,
        MiddlewareRegistry $middlewareRegistry,
        array $controllers,
        array $callChain,
        array $models,
        string $projectRoot = '',
        array $dbQueryMap = [],
    ): Graph {
        if ($projectRoot !== '') {
            $this->psr4Map = $this->buildFullPsr4Map($projectRoot);
            $this->classSearchBases = $this->projectStructure->discoverClassSearchBases($projectRoot);
        } else {
            $this->psr4Map = [];
            $this->classSearchBases = [];
        }
        $this->classMetrics = [];
        $this->dbQueryMap = $dbQueryMap;
        $this->lightMode = count($routes) >= self::LIGHT_MODE_ROUTE_THRESHOLD
            || count($callChain) >= self::LIGHT_MODE_CALL_EDGE_THRESHOLD;
        $this->graph->setMeta([
            'project' => $projectName,
            'analyzedAt' => date('c'),
            'lightMode' => $this->lightMode,
        ]);

        // ── 1. Routes, Controllers, Actions, Middlewares ──────────────────────

        foreach ($routes as $route) {
            $routeId = $this->routeId($route);
            $this->addRouteNode($route, $routeId);

            if ($route->controller !== 'Closure' && $route->controller !== '') {
                $controllerId = $this->controllerId($route->controller);
                $this->addControllerNode($route->controller, $controllers[$route->controller] ?? null, $controllerId);
                $this->addEdge($routeId, $controllerId, 'calls', 'route-to-controller');

                if ($route->action) {
                    $actionId = $this->actionId($route->controller, $route->action);
                    $controllerDef = $controllers[$route->controller] ?? null;
                    $this->addActionNode($route->controller, $route->action, $controllerDef, $actionId);
                    $this->addEdge($controllerId, $actionId, 'handles', 'controller-to-action');
                }
            }

            // Middleware
            $resolvedMiddlewares = $this->resolveMiddlewares($route->middlewares, $middlewareRegistry);
            foreach ($resolvedMiddlewares as $mw) {
                $mwId = $this->middlewareId($mw);
                $this->addMiddlewareNode($mw, $mwId);
                $this->addEdge($routeId, $mwId, 'guarded by', 'route-to-middleware');
            }
        }

        // ── 2. Deep call chain edges ──────────────────────────────────────────
        //
        // Each CallChainEdge looks like:
        //   OrderController::store  →  OrderService::createOrder  (service)
        //   OrderService::createOrder → OrderRepository::create   (repository)
        //   OrderRepository::create  → Order::create              (model)
        //   OrderService::createOrder → SendOrderConfirmationJob::handle (job)

        foreach ($callChain as $edge) {
            $callerNode = $this->nodeIdForHop($edge->callerFqcn, $edge->callerMethod);
            $calleeNode = $this->nodeIdForHop($edge->calleeFqcn, $edge->calleeMethod);

            // Ensure callee node exists
            $this->ensureNode($edge->calleeFqcn, $edge->calleeMethod, $edge->type, $models);

            // Ensure caller node exists (may be a service/repo itself in deep chains)
            // The controller action node is already created in step 1; for others, create here.
            if (! $this->graph->hasNode($callerNode)) {
                // Determine caller type by re-classifying
                $callerType = $this->classifyFqcn($edge->callerFqcn);
                $this->ensureNode($edge->callerFqcn, $edge->callerMethod, $callerType, $models);
            }

            $edgeLabel = $this->edgeLabelForType($edge->type);
            $edgeType = 'action-to-'.$edge->type;

            $this->addEdge($callerNode, $calleeNode, $edgeLabel, $edgeType);
        }

        // ── 3. Model-to-model relationships and model-fired events ───────────

        foreach ($models as $modelFqcn => $modelDef) {
            $modelId = $this->modelId($modelFqcn);
            if (! $this->graph->hasNode($modelId)) {
                $this->addModelNode($modelFqcn, $modelDef, $modelId);
            }

            foreach ($modelDef->firedEvents as $eventFqcn) {
                $eventId = $this->eventId($eventFqcn);
                $this->addEventNode($eventFqcn, $eventId);
                $this->addEdge($modelId, $eventId, 'fires', 'model-to-event');
            }
            foreach ($modelDef->relationships as $rel) {
                $relatedId = $this->modelId($rel['related']);
                if (! $this->graph->hasNode($relatedId)) {
                    $this->addModelNode($rel['related'], null, $relatedId);
                }
                $this->addEdge($modelId, $relatedId, $rel['type'], 'model-relationship');
            }
        }

        // ── 4. Fat-class pass ─────────────────────────────────────────────────
        // After all nodes are built, mark controllers/services as fat classes.

        if (! $this->lightMode) {
            foreach ($this->classMetrics as $nodeId => $agg) {
                if (! $this->graph->hasNode($nodeId)) {
                    continue;
                }
                if ($agg['totalLines'] > 300 || $agg['methodCount'] > 10) {
                    $node = $this->graph->getNode($nodeId);
                    if ($node !== null) {
                        $this->graph->updateNodeData($nodeId, array_merge(
                            $node->data,
                            ['fatClass' => true, 'classMetrics' => $agg],
                        ));
                    }
                }
            }
        }

        return $this->graph;
    }

    // ── Node creation helpers ─────────────────────────────────────────────────

    /**
     * Given a callee from a CallChainEdge, create the appropriate typed node.
     */
    private function ensureNode(string $fqcn, string $method, string $type, array $models): void
    {
        $id = $this->nodeIdForHop($fqcn, $method);
        if ($this->graph->hasNode($id)) {
            return;
        }

        switch ($type) {
            case 'model':
                $short = class_basename($fqcn);
                $file = isset($models[$fqcn]) ? $models[$fqcn]->file : $this->resolveFile($fqcn);
                $flowSteps = $this->canCollectDeepFlow() && $method !== ''
                    ? $this->extractMethodFlowSteps($fqcn, $method)
                    : [];
                $this->graph->addNode(new Node($id, 'model', $method ? "{$short}::{$method}" : $short, [
                    'fqcn' => $fqcn,
                    'method' => $method,
                    'file' => $file,
                    'flowSteps' => $flowSteps,
                    'visibility' => 'public',
                    ...($this->hasN1InSteps($flowSteps) ? ['hasN1' => true] : []),
                ]));
                break;

            case 'job':
                $short = class_basename($fqcn);
                $file = $this->resolveFile($fqcn);
                $flowSteps = $this->canCollectDeepFlow() && $method !== ''
                    ? $this->extractMethodFlowSteps($fqcn, $method)
                    : [];
                $this->graph->addNode(new Node($id, 'job', $method ? "{$short}@{$method}" : $short, [
                    'fqcn' => $fqcn,
                    'method' => $method,
                    'file' => $file,
                    'flowSteps' => $flowSteps,
                    'visibility' => 'public',
                    ...($this->hasN1InSteps($flowSteps) ? ['hasN1' => true] : []),
                ]));
                break;

            case 'event':
                $short = class_basename($fqcn);
                $file = $this->resolveFile($fqcn);
                $flowSteps = $this->canCollectDeepFlow() && $method !== ''
                    ? $this->extractMethodFlowSteps($fqcn, $method)
                    : [];
                $this->graph->addNode(new Node($id, 'event', $method ? "{$short}@{$method}" : $short, [
                    'fqcn' => $fqcn,
                    'method' => $method,
                    'file' => $file,
                    'flowSteps' => $flowSteps,
                    'visibility' => 'public',
                    ...($this->hasN1InSteps($flowSteps) ? ['hasN1' => true] : []),
                ]));
                break;

            case 'repository':
                $short = class_basename($fqcn);
                $file = $this->resolveFile($fqcn);
                $flowSteps = $this->canCollectDeepFlow() ? $this->extractMethodFlowSteps($fqcn, $method) : [];
                $repoMetrics = $this->canCollectDeepFlow() ? $this->extractMethodMetrics($fqcn, $method) : [];
                $this->graph->addNode(new Node($id, 'service', "{$short}@{$method}", [
                    'fqcn' => $fqcn,
                    'method' => $method,
                    'subtype' => 'repository',
                    'file' => $file,
                    'flowSteps' => $flowSteps,
                    'visibility' => $this->canCollectDeepFlow() ? $this->extractVisibility($fqcn, $method) : 'public',
                    ...($repoMetrics ? ['metrics' => $repoMetrics] : []),
                    ...($this->hasN1InSteps($flowSteps) ? ['hasN1' => true] : []),
                    ...($this->isFatMethod($repoMetrics) ? ['fatMethod' => true] : []),
                ]));
                break;

            default: // service
                $short = class_basename($fqcn);
                $file = $this->resolveFile($fqcn);
                $flowSteps = $this->canCollectDeepFlow() ? $this->extractMethodFlowSteps($fqcn, $method) : [];
                $svcMetrics = $this->canCollectDeepFlow() ? $this->extractMethodMetrics($fqcn, $method) : [];
                $this->graph->addNode(new Node($id, 'service', "{$short}@{$method}", [
                    'fqcn' => $fqcn,
                    'method' => $method,
                    'subtype' => 'service',
                    'file' => $file,
                    'flowSteps' => $flowSteps,
                    'visibility' => $this->canCollectDeepFlow() ? $this->extractVisibility($fqcn, $method) : 'public',
                    ...($svcMetrics ? ['metrics' => $svcMetrics] : []),
                    ...($this->hasN1InSteps($flowSteps) ? ['hasN1' => true] : []),
                    ...($this->isFatMethod($svcMetrics) ? ['fatMethod' => true] : []),
                ]));
                break;
        }
    }

    /**
     * The node ID for a hop. Controller actions already have a known ID from step 1;
     * we use the same format so edges connect correctly.
     */
    private function nodeIdForHop(string $fqcn, string $method): string
    {
        // Controller action nodes use the existing format
        if ($this->isController($fqcn)) {
            return $this->actionId($fqcn, $method);
        }

        // Everything else: fqcn::method
        return strtolower(preg_replace('/[^a-zA-Z0-9_]/', '_', $fqcn)).'::'.$method;
    }

    private function isController(string $fqcn): bool
    {
        return str_contains($fqcn, 'Controller') || str_contains($fqcn, '\\Http\\');
    }

    private function classifyFqcn(string $fqcn): string
    {
        if ($this->isController($fqcn)) {
            return 'action';
        }
        if (str_contains($fqcn, 'Repository') || str_contains($fqcn, '\\Repositories\\')) {
            return 'repository';
        }
        if (str_contains($fqcn, 'Job') || str_contains($fqcn, '\\Jobs\\')) {
            return 'job';
        }
        if (str_contains($fqcn, 'Event') || str_contains($fqcn, '\\Events\\')) {
            return 'event';
        }
        if (str_contains($fqcn, '\\Models\\') || str_contains($fqcn, '\\Model\\')) {
            return 'model';
        }

        return 'service';
    }

    private function edgeLabelForType(string $type): string
    {
        return match ($type) {
            'model' => 'queries',
            'job' => 'dispatches',
            'event' => 'dispatches',
            'repository' => 'calls',
            default => 'calls',
        };
    }

    // ── Existing node adders ──────────────────────────────────────────────────

    private function addRouteNode(RouteDefinition $route, string $id): void
    {
        if ($this->graph->hasNode($id)) {
            return;
        }

        $nodeData = [
            'method' => $route->method,
            'uri' => $route->uri,
            'name' => $route->name,
            'file' => $route->file,
            'line' => $route->line,
        ];

        if ($route->closureNode !== null) {
            $flowSteps = $this->flowExtractor->extractFromClosure($route->closureNode);
            if ($flowSteps !== []) {
                $nodeData['flowSteps'] = $flowSteps;
            }
            if ($this->hasN1InSteps($flowSteps)) {
                $nodeData['hasN1'] = true;
            }
        }

        $this->graph->addNode(new Node($id, 'route', "{$route->method} {$route->uri}", $nodeData));
    }

    private function addControllerNode(string $fqcn, ?ControllerDefinition $def, string $id): void
    {
        if ($this->graph->hasNode($id)) {
            return;
        }
        $short = class_basename($fqcn);
        $this->graph->addNode(new Node($id, 'controller', $short, [
            'fqcn' => $fqcn,
            'file' => $def !== null ? $def->file : $this->resolveFile($fqcn),
        ]));
    }

    private function addActionNode(string $fqcn, string $action, ?ControllerDefinition $def, string $id): void
    {
        if ($this->graph->hasNode($id)) {
            return;
        }
        $short = class_basename($fqcn);

        $flowSteps = [];
        $metrics = [];
        if ($def !== null) {
            foreach ($def->methods as $methodDef) {
                if ($methodDef->name === $action && $methodDef->ast !== null) {
                    $flowSteps = $this->flowExtractor->extract($methodDef->ast, $def->useMap);
                    if (! $this->lightMode) {
                        $metrics = $this->flowExtractor->metrics($methodDef->ast);
                    }
                    break;
                }
            }
        }

        $controllerId = $this->controllerId($fqcn);
        if (! empty($metrics)) {
            $this->classMetrics[$controllerId] ??= ['totalLines' => 0, 'methodCount' => 0];
            $this->classMetrics[$controllerId]['totalLines'] += $metrics['lineCount'];
            $this->classMetrics[$controllerId]['methodCount'] += 1;
        }

        $nodeData = [
            'fqcn' => $fqcn,
            'method' => $action,
            'file' => $def !== null ? $def->file : $this->resolveFile($fqcn),
            'flowSteps' => $flowSteps,
            'visibility' => $this->findActionVisibility($action, $def),
        ];

        if (! empty($metrics)) {
            $nodeData['metrics'] = $metrics;
        }

        if ($this->hasN1InSteps($flowSteps)) {
            $nodeData['hasN1'] = true;
        }

        if ($this->isFatMethod($metrics)) {
            $nodeData['fatMethod'] = true;
        }

        $actionKey = $fqcn.'::'.$action;
        if (! empty($this->dbQueryMap[$actionKey])) {
            $nodeData['dbQueries'] = array_values(
                array_map(fn (DbQuery $q) => $q->toArray(), $this->dbQueryMap[$actionKey])
            );
        }

        $this->graph->addNode(new Node($id, 'action', "{$short}@{$action}", $nodeData));
    }

    private function findActionVisibility(string $action, ?ControllerDefinition $def): string
    {
        if ($def === null) {
            return 'public';
        }
        foreach ($def->methods as $m) {
            if ($m->name === $action) {
                return $m->visibility;
            }
        }

        return 'public';
    }

    private function extractVisibility(string $fqcn, string $method): string
    {
        $file = $this->resolveFile($fqcn);
        if ($file === '' || ! file_exists($file)) {
            return 'public';
        }

        if (! isset($this->parseCache[$file])) {
            $this->parseCache[$file] = $this->parser->parse($file);
        }
        $parsed = $this->parseCache[$file];
        if (! $parsed || ! $parsed['ast']) {
            return 'public';
        }

        $traverser = new NodeTraverser;
        $finder = new class($method) extends NodeVisitorAbstract
        {
            public string $visibility = 'public';

            public function __construct(private string $target) {}

            public function enterNode(PhpNode $node): ?int
            {
                if ($node instanceof PhpNode\Stmt\ClassMethod
                    && $node->name->toString() === $this->target) {
                    if ($node->isPrivate()) {
                        $this->visibility = 'private';
                    } elseif ($node->isProtected()) {
                        $this->visibility = 'protected';
                    } else {
                        $this->visibility = 'public';
                    }

                    return NodeVisitor::STOP_TRAVERSAL;
                }

                return null;
            }
        };
        $traverser->addVisitor($finder);
        $traverser->traverse($parsed['ast']);

        return $finder->visibility;
    }

    private function hasN1InSteps(array $steps): bool
    {
        foreach ($steps as $step) {
            if ($step['n1'] ?? false) {
                return true;
            }
            if ($step['type'] === 'if') {
                if ($this->hasN1InSteps($step['then'] ?? [])) {
                    return true;
                }
                if ($this->hasN1InSteps($step['else'] ?? [])) {
                    return true;
                }
            }
            if ($step['type'] === 'loop' && isset($step['body'])) {
                if ($this->hasN1InSteps($step['body'])) {
                    return true;
                }
            }
        }

        return false;
    }

    /**
     * A method is "fat" if it has more than 30 lines OR cyclomatic complexity > 10.
     */
    private function isFatMethod(array $metrics): bool
    {
        if (empty($metrics)) {
            return false;
        }

        return ($metrics['lineCount'] > 30) || ($metrics['cyclomaticComplexity'] > 10);
    }

    private function addMiddlewareNode(string $fqcn, string $id): void
    {
        if ($this->graph->hasNode($id)) {
            return;
        }
        $short = class_basename($fqcn);
        $this->graph->addNode(new Node($id, 'middleware', $short, [
            'fqcn' => $fqcn,
            'file' => $this->resolveFile($fqcn),
        ]));
    }

    private function addModelNode(string $fqcn, ?ModelDefinition $def, string $id): void
    {
        if ($this->graph->hasNode($id)) {
            return;
        }
        $short = class_basename($fqcn);
        $this->graph->addNode(new Node($id, 'model', $short, [
            'fqcn' => $fqcn,
            'file' => $def !== null ? $def->file : $this->resolveFile($fqcn),
            'relationships' => $def !== null ? $def->relationships : [],
        ]));
    }

    private function addEventNode(string $fqcn, string $id): void
    {
        if ($this->graph->hasNode($id)) {
            return;
        }
        $short = class_basename($fqcn);
        $this->graph->addNode(new Node($id, 'event', $short, [
            'fqcn' => $fqcn,
            'file' => $this->resolveFile($fqcn),
        ]));
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private function resolveMiddlewares(array $middlewares, MiddlewareRegistry $registry): array
    {
        $resolved = [];
        foreach ($middlewares as $mw) {
            $alias = explode(':', $mw)[0];
            $resolved[] = $registry->resolveAlias($alias);
        }

        return array_unique($resolved);
    }

    private function addEdge(string $source, string $target, string $label, string $type): void
    {
        $id = "e{$this->edgeCounter}_{$source}_{$target}";
        if ($this->graph->hasEdge($id)) {
            return;
        }
        // Prevent edges to/from non-existent nodes (safety guard)
        if (! $this->graph->hasNode($source) || ! $this->graph->hasNode($target)) {
            return;
        }
        $this->graph->addEdge(new Edge($id, $source, $target, $label, $type));
        $this->edgeCounter++;
    }

    // ── Console commands ──────────────────────────────────────────────────────

    /**
     * @param  ConsoleCommandDefinition[]  $commands
     * @param  ScheduleEntry[]  $schedules
     * @param  CallChainEdge[]  $callEdges  edges discovered by tracing handle() methods
     */
    public function addConsoleCommands(array $commands, array $schedules, array $callEdges = []): void
    {
        // Build a map from command FQCN → node ID so edges can reference back to command nodes
        $classToCmdId = [];

        foreach ($commands as $cmd) {
            $id = "command::{$cmd->signature}";
            $flowSteps = [];
            $metrics = [];
            $hasN1 = false;

            if ($cmd->class) {
                if ($this->canCollectDeepFlow()) {
                    $flowSteps = $this->extractMethodFlowSteps($cmd->class, 'handle');
                    $metrics = $this->extractMethodMetrics($cmd->class, 'handle');
                }
                $hasN1 = $this->hasN1InSteps($flowSteps);
                $classToCmdId[$cmd->class] = $id;
            }

            if (! $this->graph->hasNode($id)) {
                $this->graph->addNode(new Node($id, 'command', $cmd->signature, [
                    'signature' => $cmd->signature,
                    'description' => $cmd->description,
                    'class' => $cmd->class,
                    'file' => $cmd->file,
                    'source' => $cmd->source,
                    'flowSteps' => $flowSteps,
                    'metrics' => $metrics ?: null,
                    'hasN1' => $hasN1,
                    'fatMethod' => ! empty($metrics) && $this->isFatMethod($metrics),
                ]));
            }
        }

        // Wire up call chain edges from command handle() methods
        foreach ($callEdges as $edge) {
            $callerNode = $classToCmdId[$edge->callerFqcn]
                ?? $this->nodeIdForHop($edge->callerFqcn, $edge->callerMethod);
            $calleeNode = $this->nodeIdForHop($edge->calleeFqcn, $edge->calleeMethod);

            $this->ensureNode($edge->calleeFqcn, $edge->calleeMethod, $edge->type, []);

            if (! $this->graph->hasNode($callerNode) && ! isset($classToCmdId[$edge->callerFqcn])) {
                $callerType = $this->classifyFqcn($edge->callerFqcn);
                $this->ensureNode($edge->callerFqcn, $edge->callerMethod, $callerType, []);
            }

            $this->addEdge($callerNode, $calleeNode, $this->edgeLabelForType($edge->type), 'command-to-'.$edge->type);
        }

        foreach ($schedules as $entry) {
            $schedId = 'schedule::'.md5($entry->type.$entry->target.$entry->frequency);

            if (! $this->graph->hasNode($schedId)) {
                $label = $entry->frequency
                    ? "{$entry->target} ({$entry->frequency})"
                    : $entry->target;

                $this->graph->addNode(new Node($schedId, 'schedule', $label, [
                    'type' => $entry->type,
                    'target' => $entry->target,
                    'frequency' => $entry->frequency,
                    'file' => $entry->file,
                ]));
            }

            // Edge: schedule → command/job node if it exists
            $targetId = "command::{$entry->target}";
            if ($this->graph->hasNode($targetId)) {
                $this->addEdge($schedId, $targetId, 'runs', 'schedule-to-command');
            }
        }
    }

    // ── Broadcast channels ────────────────────────────────────────────────────

    /**
     * @param  ChannelDefinition[]  $channels
     * @param  CallChainEdge[]  $callEdges  edges discovered by tracing __invoke()/__join() methods
     */
    public function addChannels(array $channels, array $callEdges = []): void
    {
        // Build a map from channel FQCN → node ID
        $classToChannelId = [];

        foreach ($channels as $ch) {
            $id = 'channel::'.md5($ch->name);
            $flowSteps = [];

            if ($ch->class) {
                // Try __invoke first (class-based channels), then join() as fallback
                if ($this->canCollectDeepFlow()) {
                    $flowSteps = $this->extractMethodFlowSteps($ch->class, '__invoke');
                    if (empty($flowSteps)) {
                        $flowSteps = $this->extractMethodFlowSteps($ch->class, 'join');
                    }
                }
                $classToChannelId[$ch->class] = $id;
            }

            if (! $this->graph->hasNode($id)) {
                $this->graph->addNode(new Node($id, 'channel', $ch->name, [
                    'name' => $ch->name,
                    'class' => $ch->class,
                    'file' => $ch->file,
                    'flowSteps' => $flowSteps,
                ]));
            }
        }

        // Wire up call chain edges from channel authorization methods
        foreach ($callEdges as $edge) {
            $callerNode = $classToChannelId[$edge->callerFqcn]
                ?? $this->nodeIdForHop($edge->callerFqcn, $edge->callerMethod);
            $calleeNode = $this->nodeIdForHop($edge->calleeFqcn, $edge->calleeMethod);

            $this->ensureNode($edge->calleeFqcn, $edge->calleeMethod, $edge->type, []);

            if (! $this->graph->hasNode($callerNode) && ! isset($classToChannelId[$edge->callerFqcn])) {
                $callerType = $this->classifyFqcn($edge->callerFqcn);
                $this->ensureNode($edge->callerFqcn, $edge->callerMethod, $callerType, []);
            }

            $this->addEdge($callerNode, $calleeNode, $this->edgeLabelForType($edge->type), 'channel-to-'.$edge->type);
        }
    }

    // ── ID generators ─────────────────────────────────────────────────────────

    private function routeId(RouteDefinition $r): string
    {
        return "route::{$r->method}::{$r->uri}";
    }

    private function controllerId(string $fqcn): string
    {
        return "controller::{$fqcn}";
    }

    private function actionId(string $fqcn, string $action): string
    {
        return "action::{$fqcn}::{$action}";
    }

    private function middlewareId(string $fqcn): string
    {
        return "middleware::{$fqcn}";
    }

    private function modelId(string $fqcn): string
    {
        return "model::{$fqcn}";
    }

    private function eventId(string $fqcn): string
    {
        return "event::{$fqcn}";
    }

    private function canCollectDeepFlow(): bool
    {
        return ! $this->lightMode;
    }
}

function class_basename(string $fqcn): string
{
    $parts = explode('\\', $fqcn);

    return end($parts);
}
